/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole_20 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] o,
    output reg [2:0] error
  );
  
  
  
  always @* begin
    o = 1'h0;
    error = 1'h0;
    
    case (alufn[0+3-:4])
      4'h8: begin
        o = a & b;
      end
      4'he: begin
        o = a | b;
      end
      4'h6: begin
        o = a ^ b;
      end
      4'ha: begin
        o = a;
      end
      4'hc: begin
        o = b;
      end
      default: begin
        error = 3'h4;
      end
    endcase
  end
endmodule
