/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module modulo_24 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] o,
    output reg [2:0] error
  );
  
  
  
  reg [15:0] quotient;
  
  always @* begin
    o = 1'h0;
    error = 1'h0;
    quotient = 1'h0;
    if (b == 1'h0) begin
      error = 3'h3;
    end else begin
      quotient = a / b;
      o = a - (b * quotient);
    end
  end
endmodule
