/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module stateCounter_1 (
    input clk,
    input rst,
    output reg easy,
    output reg hard,
    output reg hold
  );
  
  
  
  reg [26:0] M_easyCounter_d, M_easyCounter_q = 1'h0;
  reg [25:0] M_hardCounter_d, M_hardCounter_q = 1'h0;
  reg [0:0] M_holdCounter_d, M_holdCounter_q = 1'h0;
  
  always @* begin
    M_hardCounter_d = M_hardCounter_q;
    M_easyCounter_d = M_easyCounter_q;
    M_holdCounter_d = M_holdCounter_q;
    
    easy = M_easyCounter_q[26+0-:1];
    M_easyCounter_d = M_easyCounter_q + 1'h1;
    if (M_easyCounter_q[26+0-:1] == 1'h1) begin
      M_easyCounter_d[26+0-:1] = 1'h0;
    end
    hard = M_hardCounter_q[25+0-:1];
    M_hardCounter_d = M_hardCounter_q + 1'h1;
    if (M_hardCounter_q[25+0-:1] == 1'h1) begin
      M_hardCounter_d[25+0-:1] = 1'h0;
    end
    hold = M_holdCounter_q[0+0-:1];
    M_holdCounter_d = M_holdCounter_q + 1'h1;
    if (M_holdCounter_q[0+0-:1] == 1'h1) begin
      M_holdCounter_d[0+0-:1] = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_easyCounter_q <= 1'h0;
      M_hardCounter_q <= 1'h0;
      M_holdCounter_q <= 1'h0;
    end else begin
      M_easyCounter_q <= M_easyCounter_d;
      M_hardCounter_q <= M_hardCounter_d;
      M_holdCounter_q <= M_holdCounter_d;
    end
  end
  
endmodule
